// Code generated by tools/gencatalog. DO NOT EDIT.

package apperr

// Catalog lists every error code constructed in this tree, with the
// properties the catalog test asserts on. Regenerate with `task gen-catalog`.
var Catalog = []Entry{
	{Code: "AOS_CONFIG_FIELD_FORBIDDEN", Package: "internal/domain/config", File: "internal/domain/config/errors.go", Line: 11, Status: 403, Causer: "config.Service.Update", CTA: true, Issues: []string{"allowed", "field"}},
	{Code: "AOS_CONFIG_FIELD_UNKNOWN", Package: "internal/domain/config", File: "internal/domain/config/errors.go", Line: 25, Status: 400, Causer: "config.Service.Update", CTA: true, Issues: []string{"field"}},
	{Code: "AOS_CONFIG_LOAD_FAILED", Package: "internal/domain/config", File: "internal/domain/config/errors.go", Line: 49, Status: 500, Causer: "config.Service.load", CTA: false},
	{Code: "AOS_CONFIG_REVEAL_DENIED", Package: "internal/domain/config", File: "internal/domain/config/errors.go", Line: 38, Status: 403, Causer: "config.Service.Get", CTA: true},
	{Code: "AOS_CONFIG_SAVE_FAILED", Package: "internal/domain/config", File: "internal/domain/config/errors.go", Line: 57, Status: 500, Causer: "config.Service.Update", CTA: false},
	{Code: "AOS_INTERNAL_PANIC", Package: "internal/core/safe", File: "internal/core/safe/safe.go", Line: 67, Status: 500, Causer: "<dynamic>", CTA: false},
	{Code: "AOS_SECRET_PERMISSION_UNSAFE", Package: "internal/core/config", File: "internal/core/config/secure.go", Line: 50, Status: 500, Causer: "config.WriteSecret", CTA: false, Issues: []string{"mode", "path"}},
	{Code: "AOS_SECRET_WRITE_FAILED", Package: "internal/core/config", File: "internal/core/config/secure.go", Line: 34, Status: 500, Causer: "config.WriteSecret", CTA: false, Issues: []string{"path"}},
	{Code: "AOS_STATE_DIR_UNWRITABLE", Package: "internal/core/config", File: "internal/core/config/paths.go", Line: 99, Status: 500, Causer: "config.Paths.Ensure", CTA: false, Issues: []string{"path"}},
	{Code: "AOS_STATE_FOREIGN_ROOT", Package: "internal/core/config", File: "internal/core/config/paths.go", Line: 60, Status: 400, Causer: "config.Paths.guardForeignState", CTA: true, Issues: []string{"root"}},
	{Code: "AOS_STATE_HOME_UNRESOLVED", Package: "internal/core/config", File: "internal/core/config/paths.go", Line: 31, Status: 500, Causer: "config.Resolve", CTA: true},
}
