// Command gentokens rebuilds the theme token contract from the stylesheet.
//
// The list of custom properties a theme must produce is what the frontend
// actually reads, and the only honest source for it is the CSS. Maintaining it
// by hand would mean a property added to a component and forgotten in the
// renderer renders an invisible element — and the element it renders invisible
// is never the one you are looking at when you notice.
package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// declaration matches a custom property being defined, not one being read:
// `--background: value` and never `var(--background)`.
var declaration = regexp.MustCompile(`(?m)^\s*(--[a-z0-9-]+)\s*:`)

func main() {
	source := "frontend/src/styles/tokens.css"
	out := "internal/domain/theme/tokens.txt"
	if len(os.Args) > 2 {
		source, out = os.Args[1], os.Args[2]
	}

	raw, err := os.ReadFile(source) //nolint:gosec // a path this command is given
	if err != nil {
		fail(err)
	}

	seen := map[string]bool{}
	for _, match := range declaration.FindAllStringSubmatch(string(raw), -1) {
		seen[match[1]] = true
	}
	if len(seen) == 0 {
		fail(fmt.Errorf("%s declares no custom properties; the contract would be empty", source))
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# GENERATED by `task gen-tokens` from the CSS custom properties the frontend\n")
	b.WriteString("# reads. Do not edit by hand: the point of generating it is that a property a\n")
	b.WriteString("# component consumes and no theme defines fails the build instead of rendering\n")
	b.WriteString("# something invisible.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Source: %s\n", source)
	for _, name := range names {
		b.WriteString(name)
		b.WriteString("\n")
	}

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil { //nolint:gosec // generated source
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "gentokens: %d tokens → %s\n", len(names), out)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gentokens:", err)
	os.Exit(1)
}
