// Command genschema emits the TypeScript types of every command in the
// registry.
//
// It is the property the original gets from its typed caller and the reason its
// generated schema file is three and a half thousand lines: changing a field in
// Go breaks the compilation of the frontend, rather than breaking a screen at
// runtime for whoever opens it next.
//
// The types come from the JSON Schema the registry already produces for MCP, so
// there is one description of a command and four surfaces reading it.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"

	"github.com/OWNER/aos/internal/app"
	"github.com/OWNER/aos/internal/core/command"
)

func main() {
	out := "frontend/src/lib/schema.ts"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}

	// The registry is built the same way the daemon builds it, so what is
	// generated is what the application actually publishes. A registry
	// assembled by hand here would be a second description that could drift.
	built, err := app.New(app.Options{WorkspaceRoot: os.TempDir()})
	if err != nil {
		fail(err)
	}
	defer func() { _ = built.Close() }()

	rendered, err := render(built.Registry)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(out, []byte(rendered), 0o644); err != nil { //nolint:gosec // generated source, read by everybody who builds
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "genschema: %d commands → %s\n", built.Registry.Len(), out)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genschema:", err)
	os.Exit(1)
}

func render(reg *command.Registry) (string, error) {
	var b strings.Builder
	b.WriteString(`// GENERATED by \x60task gen-schema\x60. Do not edit.
//
// Every command the application publishes, as the input it takes and the output
// it returns. The generator reads the same registry the CLI, MCP and HTTP
// surfaces read, so a field changed in Go fails the build here rather than
// failing a screen for whoever opens it next.

`)
	b.WriteString("export interface CommandMap {\n")

	descriptors := reg.Sorted()
	sort.Slice(descriptors, func(i, j int) bool { return descriptors[i].Key() < descriptors[j].Key() })

	for _, d := range descriptors {
		input, err := typeOf(d.InputSchema())
		if err != nil {
			return "", fmt.Errorf("%s: %w", d.Key(), err)
		}
		if summary := d.Summary(); summary != "" {
			fmt.Fprintf(&b, "  /** %s */\n", summary)
		}
		// The output is unknown rather than invented. The registry describes
		// what a command takes, not what it returns, and a hand-written shape
		// here would be the one thing in this file nobody regenerates.
		fmt.Fprintf(&b, "  %q: { input: %s; output: unknown };\n", d.Key(), input)
	}
	b.WriteString("}\n\n")

	b.WriteString(`export type CommandKey = keyof CommandMap;
export type CommandInput<K extends CommandKey> = CommandMap[K]["input"];
export type CommandOutput<K extends CommandKey> = CommandMap[K]["output"];

/** Every command key, for a runtime check that the binary has what this build expects. */
export const COMMAND_KEYS = [
`)
	for _, d := range descriptors {
		fmt.Fprintf(&b, "  %q,\n", d.Key())
	}
	b.WriteString("] as const;\n")

	return strings.ReplaceAll(b.String(), `\x60`, "`"), nil
}

// typeOf renders a JSON Schema as a TypeScript type.
//
// It handles the shapes the command layer actually produces — objects, arrays,
// the primitives, enums and free-form maps — and falls back to unknown for
// anything else. Falling back is deliberate: a generator that guessed would
// produce a type that compiles and lies.
func typeOf(s *jsonschema.Schema) (string, error) {
	if s == nil {
		return "Record<string, unknown>", nil
	}
	switch {
	case len(s.Enum) > 0:
		parts := make([]string, 0, len(s.Enum))
		for _, raw := range s.Enum {
			literal, err := json.Marshal(raw)
			if err != nil {
				return "", err
			}
			parts = append(parts, string(literal))
		}
		return strings.Join(parts, " | "), nil
	case s.Type == "object" || len(s.Properties) > 0:
		return object(s)
	case s.Type == "array":
		item, err := typeOf(s.Items)
		if err != nil {
			return "", err
		}
		return item + "[]", nil
	case s.Type == "string":
		return "string", nil
	case s.Type == "number" || s.Type == "integer":
		return "number", nil
	case s.Type == "boolean":
		return "boolean", nil
	default:
		return "unknown", nil
	}
}

func object(s *jsonschema.Schema) (string, error) {
	if len(s.Properties) == 0 {
		// A free-form object. The additionalProperties schema, when there is
		// one, says what the values are.
		if s.AdditionalProperties != nil {
			value, err := typeOf(s.AdditionalProperties)
			if err != nil {
				return "", err
			}
			return "Record<string, " + value + ">", nil
		}
		return "Record<string, unknown>", nil
	}

	required := map[string]bool{}
	for _, name := range s.Required {
		required[name] = true
	}
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("{\n")
	for _, name := range names {
		field := s.Properties[name]
		rendered, err := typeOf(field)
		if err != nil {
			return "", err
		}
		if field != nil && field.Description != "" {
			fmt.Fprintf(&b, "    /** %s */\n", oneLine(field.Description))
		}
		optional := "?"
		if required[name] {
			optional = ""
		}
		fmt.Fprintf(&b, "    %q%s: %s;\n", name, optional, rendered)
	}
	b.WriteString("  }")
	return b.String(), nil
}

// oneLine flattens a description so it fits in a single-line comment. A
// description with a newline in it would close the comment early and take the
// rest of the field with it.
func oneLine(s string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(s, "*/", "* /")), " ")
}
