// Package view is the declarative interface layer: screens described as data,
// validated against the design system's own catalog, and rendered by the
// frontend without a build or a deploy.
package view

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"
)

// componentsJSON is generated from the React catalog by
// frontend/scripts/gen-components.mjs and regenerated by `task gen-components`.
// `task check` fails if it drifts from what is committed, which is what stops a
// component removed in React from staying reachable here.
//
//go:embed components.json
var componentsJSON []byte

// ComponentSpec is the contract between this domain and the React design
// system: what a component is called, what it is for, and what its props are.
//
// Props is JSON Schema rather than a Go struct because the source is a zod
// schema written next to the component. Converting it to a bespoke Go shape
// would be a second description of the same thing, free to disagree with the
// first.
type ComponentSpec struct {
	Name            string         `json:"name"`
	Description     string         `json:"description"`
	Category        string         `json:"category"` // layout | data | input | feedback | navigation | typography | other
	Props           map[string]any `json:"props"`
	Slots           []string       `json:"slots"`
	AcceptsChildren bool           `json:"acceptsChildren"`
}

var (
	catalogOnce sync.Once
	catalog     []ComponentSpec
	catalogByID map[string]ComponentSpec
)

func loadCatalog() {
	if err := json.Unmarshal(componentsJSON, &catalog); err != nil {
		// The file is embedded: if it does not parse, it did not parse when the
		// binary was built, and starting anyway would hide a broken build.
		panic(fmt.Sprintf("view: components.json does not parse: %v", err))
	}
	catalogByID = make(map[string]ComponentSpec, len(catalog))
	for _, s := range catalog {
		catalogByID[s.Name] = s
	}
}

// Catalog returns every component the design system publishes, sorted by name.
func Catalog() []ComponentSpec {
	catalogOnce.Do(loadCatalog)
	out := make([]ComponentSpec, len(catalog))
	copy(out, catalog)
	return out
}

// LookupComponent finds one component by name.
func LookupComponent(name string) (ComponentSpec, bool) {
	catalogOnce.Do(loadCatalog)
	s, ok := catalogByID[name]
	return s, ok
}
