package workspace

import (
	"context"
	"path"
	"strings"

	"github.com/OWNER/aos/internal/core/build"
	"github.com/OWNER/aos/internal/core/collections"
	"github.com/OWNER/aos/internal/core/env"
)

// ManagedDirs is the directory skeleton created inside the user's repository.
//
// It is deliberately not derived from collections.WorkspaceDirs(): that
// function answers "where may a record live", which includes locations only
// created on demand (tasks, chats, runs). This list answers a different
// question — "what does an empty workspace look like to a person opening the
// repository" — and the answer is the original's five directories plus views,
// which the declarative view layer will need.
var ManagedDirs = []string{
	"agents",
	"skills",
	"instructions",
	"templates",
	"collections",
	"views",
}

// The markers that delimit the section this system owns inside a file it does
// not own. Everything outside them belongs to the user and is never touched.
var (
	managedStart = "# <" + build.EnvPrefix + "_MANAGED_SECTION>"
	managedEnd   = "# </" + build.EnvPrefix + "_MANAGED_SECTION>"
)

// ScaffoldReport says what a scaffold run actually did. It exists because the
// operation is idempotent, and "created nothing" is a meaningful answer that a
// silent success would hide.
type ScaffoldReport struct {
	CreatedDirs []string `json:"createdDirs,omitempty" jsonschema:"Directories this run created, relative to the workspace root."`
	EnvFiles    []string `json:"envFiles,omitempty" jsonschema:"Environment files whose managed block was written."`
	GitInit     bool     `json:"gitInit" jsonschema:"Whether a Git repository was initialised by this run."`
	GitWarning  string   `json:"gitWarning,omitempty" jsonschema:"Why the workspace could not be put under version control, when that failed."`
}

// scaffold lays out the workspace inside the user's repository.
//
// Every step is idempotent: running it on an existing repository adds what is
// missing and touches nothing else.
func (s *Service) scaffold(ctx context.Context, w *Workspace) (ScaffoldReport, error) {
	var report ScaffoldReport

	root := path.Join(w.Path, collections.Root)
	for _, dir := range append([]string{""}, ManagedDirs...) {
		target := root
		if dir != "" {
			target = path.Join(root, dir)
		}
		created, err := s.fs.EnsureDir(ctx, target)
		if err != nil {
			return report, errScaffoldFailed(target, err)
		}
		if !created {
			continue
		}
		report.CreatedDirs = append(report.CreatedDirs, path.Join(collections.Root, dir))
		// The marker is what makes an empty directory survive a Git clone.
		if err := s.fs.WriteFile(ctx, path.Join(target, ".gitkeep"), ""); err != nil {
			return report, errScaffoldFailed(target, err)
		}
	}

	// The sample carries the variable without its value: it is committed, and
	// the id of one person's workspace is not the id of the next one's.
	for file, block := range map[string]string{
		".env":        managedBlock(w.ID),
		".env.sample": managedBlock(""),
	} {
		target := path.Join(w.Path, file)
		existing, err := s.fs.ReadFile(ctx, target)
		if err != nil {
			return report, errScaffoldFailed(target, err)
		}
		merged := spliceManagedBlock(existing, block)
		if merged == existing {
			continue
		}
		if err := s.fs.WriteFile(ctx, target, merged); err != nil {
			return report, errScaffoldFailed(target, err)
		}
		report.EnvFiles = append(report.EnvFiles, file)
	}
	// Map iteration is random and the report is compared in tests and printed
	// to people; both want a stable order.
	sortStrings(report.EnvFiles)

	return report, nil
}

// ensureGit puts the workspace under version control when it is not already.
//
// The original swallows every failure here. That is the wrong call: a workspace
// that is not versioned loses the single property that justifies keeping agent
// state inside the repository, and the user has no way to find out. Here the
// failure becomes a warning on the result.
func (s *Service) ensureGit(ctx context.Context, w *Workspace) (initialised bool, warning string) {
	already, err := s.git.IsRepository(ctx, w.Path)
	if err != nil {
		return false, "could not determine whether " + w.Path + " is a Git repository: " + err.Error()
	}
	if already {
		return false, ""
	}
	if err := s.git.Init(ctx, w.Path); err != nil {
		return false, "the workspace was created but is not under version control: " + err.Error()
	}
	return true, ""
}

// managedBlock renders the section this system owns inside the user's .env.
func managedBlock(workspaceID string) string {
	return strings.Join([]string{
		managedStart,
		"# Auto-generated by " + build.DisplayName + " — do not edit this block by hand.",
		"",
		"# Unique identifier of this " + build.DisplayName + " workspace.",
		env.Key(env.KeyWorkspaceID) + "=" + workspaceID,
		"",
		managedEnd,
	}, "\n")
}

// spliceManagedBlock replaces the delimited managed section and leaves every
// other byte of the file where it was.
//
// This runs against a file the user owns and may have written by hand. The
// contract is narrow on purpose: if both markers are present, replace what is
// between them; otherwise append. Anything cleverer — reordering, deduplicating,
// rewriting keys — would be this system editing someone else's file.
func spliceManagedBlock(existing, block string) string {
	start := strings.Index(existing, managedStart)
	end := strings.Index(existing, managedEnd)
	if start != -1 && end != -1 && end > start {
		return existing[:start] + block + existing[end+len(managedEnd):]
	}
	trimmed := strings.TrimRight(existing, "\n \t")
	if trimmed == "" {
		return block + "\n"
	}
	return trimmed + "\n\n" + block + "\n"
}

// sortStrings is an insertion sort over a list that never exceeds two entries.
// Reaching for the sort package for that would cost an import to save nothing.
func sortStrings(v []string) {
	for i := 1; i < len(v); i++ {
		for j := i; j > 0 && v[j] < v[j-1]; j-- {
			v[j], v[j-1] = v[j-1], v[j]
		}
	}
}
