package scan_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/OWNER/aos/internal/core/apperr/scan"
)

const sample = `package sample

import (
	"net/http"

	"github.com/OWNER/aos/internal/core/apperr"
)

func errOne() error {
	return apperr.New("SAMPLE_NOT_FOUND").
		Causer("sample.Service.Get").
		Msgf("nope").
		Issue("id", "x").
		Status(http.StatusNotFound).
		CTA(apperr.CallToAction{Label: "list"})
}

func errTwo(name string) error {
	return apperr.New("SAMPLE_BROKEN").Causer(name).Status(apperr.StatusInternalServerError)
}

func errThree() error {
	return apperr.New("SAMPLE_BARE")
}
`

const ignored = `package sample

import "github.com/OWNER/aos/internal/core/apperr"

func errInTest() error { return apperr.New("SHOULD_NOT_BE_SCANNED").Causer("t") }
`

func writeTree(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(sample), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "sample_test.go"), []byte(ignored), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

func TestScanReadsTheWholeFluentChain(t *testing.T) {
	entries, err := scan.Scan(writeTree(t))
	if err != nil {
		t.Fatal(err)
	}
	byCode := map[string]int{}
	for i, e := range entries {
		byCode[e.Code] = i
	}

	one, ok := byCode["AOS_SAMPLE_NOT_FOUND"]
	if !ok {
		t.Fatalf("codes found: %v", byCode)
	}
	e := entries[one]
	if e.Causer != "sample.Service.Get" || e.Status != 404 || !e.CTA {
		t.Errorf("chain not read: %+v", e)
	}
	if len(e.Issues) != 1 || e.Issues[0] != "id" {
		t.Errorf("issues = %v", e.Issues)
	}
	if e.File != "sample.go" || e.Line == 0 {
		t.Errorf("position = %s:%d", e.File, e.Line)
	}
}

// TestApperrStatusConstantsAreUnderstood: domain code cannot import net/http,
// so the scanner has to read apperr.StatusX as well as http.StatusX.
func TestApperrStatusConstantsAreUnderstood(t *testing.T) {
	entries, err := scan.Scan(writeTree(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.Code != "AOS_SAMPLE_BROKEN" {
			continue
		}
		if e.Status != 500 {
			t.Errorf("status = %d, want 500", e.Status)
		}
		// A causer built from a variable still counts as present.
		if e.Causer != "<dynamic>" {
			t.Errorf("causer = %q, want <dynamic>", e.Causer)
		}
		return
	}
	t.Fatal("AOS_SAMPLE_BROKEN not found")
}

func TestUnsetStatusDefaultsTo500(t *testing.T) {
	entries, err := scan.Scan(writeTree(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.Code == "AOS_SAMPLE_BARE" {
			if e.Status != 500 {
				t.Fatalf("status = %d, want the apperr.New default of 500", e.Status)
			}
			return
		}
	}
	t.Fatal("AOS_SAMPLE_BARE not found")
}

func TestTestFilesAreNotScanned(t *testing.T) {
	entries, err := scan.Scan(writeTree(t))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.Contains(e.Code, "SHOULD_NOT_BE_SCANNED") {
			t.Fatal("a _test.go file leaked into the catalog")
		}
	}
}

func TestRenderProducesCompilableSource(t *testing.T) {
	entries, err := scan.Scan(writeTree(t))
	if err != nil {
		t.Fatal(err)
	}
	out := string(scan.Render(entries))
	for _, want := range []string{
		"// Code generated by tools/gencatalog. DO NOT EDIT.",
		"package apperr",
		"var Catalog = []Entry{",
		`Code: "AOS_SAMPLE_NOT_FOUND"`,
		`Issues: []string{"id"}`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("rendered source is missing %q:\n%s", want, out)
		}
	}
}

func TestScanRejectsUnparseableSource(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "broken.go"), []byte("package ???"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := scan.Scan(root); err == nil {
		t.Fatal("expected a parse error")
	}
}
