// GENERATED by `task gen-schema`. Do not edit.
//
// Every command the application publishes, as the input it takes and the output
// it returns. The generator reads the same registry the CLI, MCP and HTTP
// surfaces read, so a field changed in Go fails the build here rather than
// failing a screen for whoever opens it next.

export interface CommandMap {
  /** Remove one entry from the log. */
  "activity_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Read one entry in full. */
  "activity_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Read the workspace inbox. */
  "activity_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to apply. Defaults to you. */
    "actor"?: string;
    /** Only this event within the namespace. Example: "status_changed". */
    "event"?: string;
    /** How many to return. Defaults to 50. */
    "limit"?: number;
    /** Only entries about this kind of thing. Example: "task". */
    "namespace"?: string;
    /** How many to skip. */
    "offset"?: number;
    /** RFC3339 instant; only entries at or after it. */
    "since"?: string;
    /** Only what you have not read yet. */
    "unread"?: boolean;
  }; output: unknown };
  /** Drop entries past the retention window. */
  "activity_purge": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Override the retention window, in days. Defaults to the configured 90. */
    "olderThanDays"?: number;
  }; output: unknown };
  /** Mark one entry as read. */
  "activity_read": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to change. Defaults to you. */
    "actor"?: string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Mark the whole inbox as read. */
  "activity_read-all": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to change. Defaults to you. */
    "actor"?: string;
  }; output: unknown };
  /** Create an agent. */
  "agents_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Communication channel bindings for this agent. */
    "channels"?: unknown;
    /** Markdown system instructions for the agent runtime. */
    "content"?: string;
    /** Orchestrator-facing summary of when to delegate to this agent. */
    "description"?: string;
    /** Unique agent identifier (slug). Lowercase, no spaces. Example: "atlas". */
    "id": string;
    /** Slug of the leader agent in a hierarchical team. */
    "leader"?: string;
    /** LLM model id for this agent. Example: "gpt-4o". */
    "model"?: string;
    /** Human-readable display name. Defaults to the slug. */
    "name"?: string;
    /** Marks the workspace orchestrator fallback for non-direct chats. */
    "orchestrator"?: boolean;
    /** LLM provider slug for this agent. Example: "openai". */
    "provider"?: string;
    /** How hard this agent should think: none, low, medium or high. Defaults to the installation's setting. */
    "reasoning"?: string;
    /** Functional role label shown in delegation prompts. */
    "role"?: string;
    /** Filesystem and execution policy. Absent means read-only with no execution at all. */
    "sandbox"?: {
    /** Which programs this agent may run. */
    "exec"?: {
    /** Binary names or absolute paths this agent may run. Example: ["git", "go"]. */
    "allow"?: unknown;
    /** Whether this agent may reach a shell. A shell makes the allowlist a suggestion, so it takes its own opt-in. */
    "allowShell"?: boolean;
    /** Command lines to refuse even for an allowed binary. Example: ["git push --force*"]. */
    "denyArgs"?: unknown;
    /** allowlist or deny-all. Defaults to deny-all. */
    "policy"?: string;
  };
    /** Any of: read, write, delete, execute. Defaults to read alone. */
    "permissions"?: unknown;
  };
    /** Voice name for speech output. */
    "voice"?: string;
  }; output: unknown };
  /** Delete an agent and everything under it. */
  "agents_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug to delete. This removes the agent's memories and routines with it. */
    "id": string;
  }; output: unknown };
  /** Read one agent, instructions included. */
  "agents_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug to retrieve. Example: "neo". */
    "id": string;
  }; output: unknown };
  /** List the agents of the workspace. */
  "agents_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Maximum number of agents to return. 0 means no limit. */
    "limit"?: number;
    /** Only agents with this functional role label. */
    "role"?: string;
    /** Only agents shipped by this skill. Omit to list the workspace's own agents and every skill's. */
    "skill"?: string;
  }; output: unknown };
  /** Resolve your own identity in this workspace. */
  "agents_me": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Change an agent. */
  "agents_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New Markdown system instructions. Replaces the body entirely. */
    "content"?: unknown;
    /** New orchestrator-facing summary. */
    "description"?: unknown;
    /** Agent slug to update. */
    "id": string;
    /** New leader slug. */
    "leader"?: unknown;
    /** New LLM model id. */
    "model"?: unknown;
    /** New display name. */
    "name"?: unknown;
    /** Whether this agent is the workspace orchestrator. */
    "orchestrator"?: unknown;
    /** New LLM provider slug. */
    "provider"?: unknown;
    /** New reasoning level: none, low, medium or high. */
    "reasoning"?: unknown;
    /** New functional role label. */
    "role"?: unknown;
    /** New filesystem and execution policy. Replaces the block entirely. */
    "sandbox"?: {
    /** Which programs this agent may run. */
    "exec"?: {
    /** Binary names or absolute paths this agent may run. Example: ["git", "go"]. */
    "allow"?: unknown;
    /** Whether this agent may reach a shell. A shell makes the allowlist a suggestion, so it takes its own opt-in. */
    "allowShell"?: boolean;
    /** Command lines to refuse even for an allowed binary. Example: ["git push --force*"]. */
    "denyArgs"?: unknown;
    /** allowlist or deny-all. Defaults to deny-all. */
    "policy"?: string;
  };
    /** Any of: read, write, delete, execute. Defaults to read alone. */
    "permissions"?: unknown;
  };
    /** New voice name. */
    "voice"?: unknown;
  }; output: unknown };
  /** Allow or refuse a waiting tool call. */
  "approvals_decide": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** True to let the call run, false to refuse it. */
    "approved": boolean;
    /** Identifier of the waiting request. */
    "id": string;
    /** Why. A refusal without one leaves the agent guessing what to try instead. */
    "reason"?: string;
    /** none, session or always. Defaults to none — approving once is not approving forever. */
    "remember"?: string;
    /** A corrected payload to run instead of the one proposed. */
    "updatedInput"?: unknown;
  }; output: unknown };
  /** List the tool calls waiting for a decision. */
  "approvals_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Register a new artifact. */
  "artifacts_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** What this artifact is. */
    "description"?: string;
    /** HTML file served as the artifact's root. A minimal one is scaffolded when omitted. */
    "entrypoint"?: string;
    /** Identifier for the new artifact. Generated when omitted. */
    "id"?: string;
    /** Human-readable name. */
    "name": string;
    /** Skill that owns this artifact, if any. */
    "skill"?: string;
    /** One of: private, workspace, by_password. Defaults to private. */
    "visibility"?: string;
  }; output: unknown };
  /** Remove an artifact. */
  "artifacts_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the artifact to delete. */
    "id": string;
  }; output: unknown };
  /** Read one artifact's configuration. */
  "artifacts_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the artifact. */
    "id": string;
  }; output: unknown };
  /** List every artifact registered in the workspace. */
  "artifacts_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Set the password a by_password artifact is shared behind. */
  "artifacts_set-password": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the artifact. */
    "id": string;
    /** New plaintext password, hashed before it is stored. */
    "password": string;
  }; output: unknown };
  /** Change an artifact's configuration. */
  "artifacts_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New description. Omit to leave unchanged. */
    "description"?: unknown;
    /** New entrypoint file. Omit to leave unchanged. */
    "entrypoint"?: unknown;
    /** Identifier of the artifact to update. */
    "id": string;
    /** New name. Omit to leave unchanged. */
    "name"?: unknown;
    /** New visibility. Omit to leave unchanged. */
    "visibility"?: unknown;
  }; output: unknown };
  /** Open a conversation. */
  "chats_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent that owns this conversation, for run transcripts. */
    "agent"?: string;
    /** External messenger to bind it to. */
    "channel"?: {
    /** Conversation identifier on the provider. */
    "chatId": string;
    /** Messaging provider slug. Example: "telegram". */
    "provider": string;
    /** User identifier on the provider. */
    "userId"?: string;
  };
    /** One of: dm, channel, task, run, external. Defaults to channel. */
    "kind"?: string;
    /** Who is in it. Empty on a workspace-visible channel means everyone. */
    "participants"?: unknown;
    /** Routine this conversation belongs to. */
    "routine"?: string;
    /** Task this conversation belongs to. */
    "task"?: string;
    /** What to call it. */
    "title": string;
    /** private or workspace. Defaults to workspace. */
    "visibility"?: string;
  }; output: unknown };
  /** Read one conversation. */
  "chats_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the conversation. */
    "chat": string;
  }; output: unknown };
  /** List conversations. */
  "chats_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Narrow to one surface: dm, channel, task, run or external. */
    "kind"?: string;
    /** Maximum number to return. Defaults to 50. */
    "limit"?: number;
    /** Filter by title, identifier, task or routine. */
    "query"?: string;
    /** Only conversations attached to this routine. */
    "routine"?: string;
    /** Only conversations attached to this task. */
    "task"?: string;
  }; output: unknown };
  /** Write to a conversation. */
  "chats_send": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Answer with this agent regardless of what the text mentions. */
    "agent"?: string;
    /** Conversation to write to. */
    "chat": string;
    /** What to say. Address a specific agent with @slug. */
    "text": string;
  }; output: unknown };
  /** Declare a new collection. */
  "collections_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** What this collection is for. */
    "description"?: string;
    /** The declared columns of a record. At least one is required. */
    "fields": unknown;
    /** md or json — how each record of this collection is laid out on disk. */
    "format": string;
    /** Declarative normalisations applied to a record on create or update. */
    "hooks"?: unknown;
    /** Identifier for the collection. Also its directory name: lowercase, digits, hyphen and underscore only. */
    "id": string;
    /** Human name of the collection. Example: "Contacts". */
    "name": string;
    /** workspace or skill. Defaults to workspace. */
    "scope"?: string;
    /** The skill this collection ships with, when Scope is skill. */
    "skill"?: string;
  }; output: unknown };
  /** Remove a collection's declaration. */
  "collections_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the collection to remove. */
    "id": string;
    /** The skill this collection ships with, when it is skill-scoped. */
    "skill"?: string;
  }; output: unknown };
  /** Read one collection's declaration. */
  "collections_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the collection. */
    "id": string;
    /** The skill this collection ships with, when it is skill-scoped. Required to resolve one — collections_list reports it on every entry. */
    "skill"?: string;
  }; output: unknown };
  /** List every declared collection. */
  "collections_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** File a new row. */
  "collections_records-create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the collection to file the record into. */
    "collection": string;
    /** The Markdown body, for a collection of format md. Ignored for json. */
    "content"?: string;
    /** The record's fields, as declared by its collection's schema. */
    "data": Record<string, unknown>;
  }; output: unknown };
  /** Remove a row. */
  "collections_records-delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the record's collection. */
    "collection": string;
    /** Identifier of the record to remove. */
    "id": string;
  }; output: unknown };
  /** Read one row. */
  "collections_records-get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the record's collection. */
    "collection": string;
    /** Identifier of the record. */
    "id": string;
  }; output: unknown };
  /** List a collection's rows. */
  "collections_records-list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the collection to list records from. */
    "collection": string;
    /** Reverse the order. */
    "desc"?: boolean;
    /** Field values a record must match, by field name. */
    "filters"?: Record<string, unknown>;
    /** Maximum number of records to return. 0 means no limit. */
    "limit"?: number;
    /** Number of matching records to skip, for pagination. */
    "offset"?: number;
    /** Name of a declared field to order by. Empty orders by path, which is stable. */
    "orderBy"?: string;
  }; output: unknown };
  /** Revalidate and rewrite a row. */
  "collections_records-update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the record's collection. */
    "collection": string;
    /** The record's new fields, replacing the old ones wholesale. */
    "data": Record<string, unknown>;
    /** Identifier of the record to rewrite. */
    "id": string;
  }; output: unknown };
  /** Write a comment on a task. */
  "comments_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The comment, in Markdown. */
    "body": string;
    /** Comment this replies to. A reply to a reply joins the same thread. */
    "parent"?: string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Remove a comment you wrote. */
  "comments_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read one comment. */
  "comments_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read a task's discussion. */
  "comments_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Rewrite a comment you wrote. */
  "comments_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The new body, in Markdown. */
    "body": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read the configuration, with secrets redacted. */
  "config_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Show secret values in full. Only honoured for a human on an interactive terminal; an agent never receives unredacted secrets. */
    "reveal"?: boolean;
  }; output: unknown };
  /** Change configuration fields by dotted path. */
  "config_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Dotted paths to set, for example {"region.timezone": "America/Sao_Paulo"}. An agent may only set fields on the agent-writable allowlist. */
    "set": Record<string, unknown>;
  }; output: unknown };
  /** Stop the daemon and start it again. */
  "gateway_restart": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Start the daemon. */
  "gateway_start": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Report whether the daemon is running. */
  "gateway_status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Stop the daemon. */
  "gateway_stop": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Create a new goal. */
  "goals_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Markdown body. */
    "content"?: string;
    /** One line summarising the outcome. */
    "description"?: string;
    /** When this goal is due, if it has a deadline. */
    "dueAt"?: unknown;
    /** How to tell this goal was actually served. */
    "measure"?: string;
    /** Project this goal belongs to, if any. */
    "project"?: string;
    /** Skill installing this goal, if any. */
    "skill"?: string;
    /** One of: active, achieved, abandoned, paused. Defaults to active. */
    "status"?: string;
    /** What this goal is. */
    "title": string;
  }; output: unknown };
  /** Remove a goal. */
  "goals_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the goal to delete. */
    "id": string;
  }; output: unknown };
  /** Read one goal in full. */
  "goals_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the goal. */
    "id": string;
  }; output: unknown };
  /** List goals matching a filter. */
  "goals_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Filter goals by project id. */
    "project"?: string;
    /** Full-text search across a goal's id and title. */
    "query"?: string;
    /** Filter by one or more statuses. */
    "status"?: unknown;
  }; output: unknown };
  /** Change a goal's fields. */
  "goals_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New body content, in Markdown. Omit to leave unchanged. */
    "content"?: unknown;
    /** New one-line summary of the outcome. Omit to leave unchanged. */
    "description"?: unknown;
    /** New due date. Omit to leave unchanged. */
    "dueAt"?: unknown;
    /** Identifier of the goal to update. */
    "id": string;
    /** New measure that makes this goal checkable rather than aspirational. Omit to leave unchanged. */
    "measure"?: unknown;
    /** New project this goal belongs to. Empty string clears it. Omit to leave unchanged. */
    "project"?: unknown;
    /** New lifecycle status: active, achieved, abandoned, or paused. Omit to leave unchanged. */
    "status"?: unknown;
    /** New title. Omit to leave unchanged. */
    "title"?: unknown;
  }; output: unknown };
  /** Declare a new workspace-wide instruction. */
  "instructions_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Markdown body of the instruction. */
    "content"?: string;
    /** What this instruction is for. */
    "description"?: string;
    /** Identifier for the instruction. Derived from Name when omitted. */
    "id"?: string;
    /** Human name of the instruction. Example: "Feature Protocol". */
    "name": string;
    /** Glob patterns matching files this instruction applies to. Empty applies to the whole workspace. */
    "paths"?: unknown;
    /** The skill this instruction ships with, when it is skill-scoped. */
    "skill"?: string;
    /** Categorization for organizational purposes. Example: standards, patterns, workflows. */
    "type"?: string;
  }; output: unknown };
  /** Remove an instruction. */
  "instructions_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the instruction to delete. */
    "id": string;
  }; output: unknown };
  /** Read one instruction in full. */
  "instructions_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the instruction. */
    "id": string;
  }; output: unknown };
  /** List instructions, optionally filtered. */
  "instructions_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Substring match over name, description and content. */
    "query"?: string;
    /** Filter to one skill's own instructions. */
    "skill"?: string;
  }; output: unknown };
  /** Change an existing instruction. */
  "instructions_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New lifecycle state. Omit to leave unchanged. */
    "active"?: unknown;
    /** New body. Omit to leave unchanged. */
    "content"?: unknown;
    /** New description. Omit to leave unchanged. */
    "description"?: unknown;
    /** Identifier of the instruction to update. */
    "id": string;
    /** New name. Omit to leave unchanged. */
    "name"?: unknown;
    /** New glob patterns, replacing the old ones wholesale. */
    "paths"?: unknown;
    /** New categorization. Omit to leave unchanged. */
    "type"?: unknown;
  }; output: unknown };
  /** Read one job. */
  "jobs_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the job. */
    "id": string;
  }; output: unknown };
  /** List the queued work. */
  "jobs_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only jobs of this handler kind. */
    "kind"?: string;
    /** How many to return, newest first. */
    "limit"?: number;
    /** One of: chat, task, routine, workspace. */
    "queue"?: string;
    /** One of: pending, claimed, succeeded, failed, dead. */
    "status"?: string;
    /** Only jobs of this workspace. */
    "workspace"?: string;
  }; output: unknown };
  /** Remove finished jobs older than the window. */
  "jobs_purge": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Override the window, in days. Defaults to 7. */
    "olderThanDays"?: number;
  }; output: unknown };
  /** Hand back work whose worker stopped reporting. */
  "jobs_recover": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** The shape of the queue right now. */
  "jobs_stats": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only jobs of this workspace. */
    "workspace"?: string;
  }; output: unknown };
  /** Search every configured marketplace registry. */
  "marketplace_discovery": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Filter to listings from this owner (the <owner> half of <owner>/<repo>). */
    "owner"?: string;
    /** Filter to listings carrying this tag. */
    "tag"?: string;
    /** Free-text search across name, description and tags. */
    "text"?: string;
  }; output: unknown };
  /** Read one listing's full manifest. */
  "marketplace_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Which configured registry to read from. Empty tries every configured registry. */
    "registry"?: string;
    /** The listing's source, "<owner>/<repo>". */
    "source": string;
  }; output: unknown };
  /** Fetch and install a skill from a registry. */
  "marketplace_install": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Version or ref to fetch. Empty fetches the registry's default. */
    "ref"?: string;
    /** Which configured registry to fetch from. Empty tries every configured registry. */
    "registry"?: string;
    /** The package's source, "<owner>/<repo>". */
    "source": string;
  }; output: unknown };
  /** Deprecate knowledge that no longer holds. */
  "memories_forget": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memory it is. Defaults to your own. */
    "agent"?: string;
    /** Identifier of the memory to deprecate. */
    "memory": string;
    /** Why this knowledge no longer holds. Be specific: a vague reason confuses your future self. */
    "reason": string;
  }; output: unknown };
  /** Map your cognitive graph. */
  "memories_graph": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose graph to map. Defaults to your own. */
    "agent"?: string;
    /** Narrow the graph to one category. */
    "category"?: string;
    /** Return only the memories with no links at all — the ones most likely to be lost. */
    "isolated"?: boolean;
    /** Maximum number of nodes. Defaults to 1000. */
    "limit"?: number;
    /** Exclude memories below this confidence. */
    "minConfidence"?: number;
    /** Glob patterns narrowing the graph to memories anchored to these files. */
    "scopes"?: unknown;
    /** strict excludes memories with no scopes; lax includes them. Defaults to lax. */
    "scopesMode"?: string;
  }; output: unknown };
  /** Scan your memories. */
  "memories_recall": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memories to read. Defaults to your own. */
    "agent"?: string;
    /** Narrow to one category. */
    "category"?: string;
    /** Reverse the ordering. */
    "desc"?: boolean;
    /** Maximum number of memories to return. Defaults to 10. */
    "limit"?: number;
    /** How many matches to skip. */
    "offset"?: number;
    /** One of: relevance, confidence, createdAt, updatedAt. Defaults to relevance when searching, and to createdAt otherwise. */
    "orderBy"?: string;
    /** Full-text search across title, description, tags and body. Every word must appear somewhere. */
    "query"?: string;
    /** Glob patterns anchoring the search to files. Example: ["internal/domain/**"]. */
    "scopes"?: unknown;
    /** strict excludes memories with no scopes; lax includes them. Defaults to lax. */
    "scopesMode"?: string;
    /** Lifecycle status to include. Defaults to active. */
    "status"?: string;
  }; output: unknown };
  /** Read one memory in full. */
  "memories_reflect": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memory it is. Defaults to your own. */
    "agent"?: string;
    /** Identifier of the memory to read. */
    "memory": string;
  }; output: unknown };
  /** Record durable knowledge. */
  "memories_store": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** One of: decision, intent, commitment, relationship, event, observation, error, learning, fact, reference, instruction, preference, context. */
    "category": string;
    /** From 0 to 1. Defaults to 1. Be honest — an inflated number is how future-you gets misled. */
    "confidence"?: unknown;
    /** The Markdown body of the memory. */
    "content"?: string;
    /** Dense, keyword-rich summary written to be found by search. */
    "description": string;
    /** RFC 3339 timestamp after which this memory stops applying. */
    "expiresAt"?: string;
    /** Identifiers of related memories. Aim for one or two whenever related traces exist. */
    "links"?: unknown;
    /** Glob patterns anchoring this memory to the files that gave rise to it. */
    "scopes"?: unknown;
    /** Memories this one replaces, each with the reason it no longer applies. */
    "supersedes"?: unknown;
    /** Labels grouping related knowledge. */
    "tags"?: unknown;
    /** Sharp, specific headline. It is what you will scan later. */
    "title": string;
  }; output: unknown };
  /** List the models the connected providers serve. */
  "models_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** One provider id. Empty asks every provider this installation has a credential for. */
    "provider"?: string;
  }; output: unknown };
  /** Create a new project. */
  "projects_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Display color. */
    "color"?: string;
    /** Markdown body. */
    "content"?: string;
    /** Short description. */
    "description"?: string;
    /** Lucide icon name, image URL, or data URI. */
    "icon"?: string;
    /** Identifier for the new project. A slug derived from name if omitted. */
    "id": string;
    /** Human-readable name. */
    "name": string;
    /** Globs this project owns, matched with doublestar. */
    "paths"?: unknown;
    /** Absolute host directory this project is bound to. Validated: must be absolute, exist, and be a directory. */
    "source"?: string;
    /** Lifecycle status: active, paused, done or archived. Defaults to active. */
    "status"?: string;
  }; output: unknown };
  /** Remove a project's own record. */
  "projects_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the project to delete. */
    "id": string;
  }; output: unknown };
  /** Read one project's full record. */
  "projects_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the project. */
    "id": string;
  }; output: unknown };
  /** List projects, optionally filtered by status. */
  "projects_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only projects in this status. Omit for every status. */
    "status"?: string;
  }; output: unknown };
  /** Change a project's describable fields. */
  "projects_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New display color. Omit to leave unchanged. */
    "color"?: unknown;
    /** New body content, in Markdown. Omit to leave unchanged. */
    "content"?: unknown;
    /** New description. Omit to leave unchanged. */
    "description"?: unknown;
    /** New display icon. Omit to leave unchanged. */
    "icon"?: unknown;
    /** Identifier of the project to update. */
    "id": string;
    /** New name. Omit to leave unchanged. */
    "name"?: unknown;
    /** New list of associated paths. Replaces the field wholesale when given. */
    "paths"?: unknown;
    /** New source directory — an absolute, existing path. Omit to leave unchanged. */
    "source"?: unknown;
    /** New lifecycle status. Omit to leave unchanged. */
    "status"?: unknown;
  }; output: unknown };
  /** Declare a routine. */
  "routines_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** The routine's prompt: what to do when it fires. */
    "content"?: string;
    /** What the routine does. Example: "Triage new bugs each morning". */
    "name": string;
    /** What it is allowed to do when it runs. */
    "scope"?: {
    /** Let this routine create tasks. */
    "allowCreateTasks": boolean;
    /** Let this routine reach outside the machine. */
    "allowExternalCalls": boolean;
    /** Exact set of tools it may use. Empty means the agent's usual registry, minus what the flags above withhold. */
    "allowedTools"?: unknown;
  };
    /** enabled or disabled. Defaults to enabled. */
    "status"?: string;
    /** What makes it fire. Without one it only fires by hand. */
    "triggers"?: unknown;
  }; output: unknown };
  /** Remove a routine and its runs. */
  "routines_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** Run a routine now. */
  "routines_fire": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Fire even if the routine is disabled. */
    "force"?: boolean;
    /** Identifier of the routine. */
    "id": string;
    /** What to hand the routine. */
    "payload"?: Record<string, unknown>;
    /** What to record as the cause. Defaults to manual. */
    "trigger"?: string;
  }; output: unknown };
  /** Read one routine. */
  "routines_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** List the routines. */
  "routines_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routines. Defaults to yours. */
    "agent"?: string;
    /** Only enabled or only disabled. */
    "status"?: string;
  }; output: unknown };
  /** Mint a new webhook token. */
  "routines_rotate": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** Read a routine's audit history. */
  "routines_runs": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
    /** How many to return, newest first. */
    "limit"?: number;
  }; output: unknown };
  /** Change a routine. */
  "routines_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** New prompt. */
    "content"?: unknown;
    /** Identifier of the routine. */
    "id": string;
    /** New name. */
    "name"?: unknown;
    /** New scope. */
    "scope"?: {
    /** Let this routine create tasks. */
    "allowCreateTasks": boolean;
    /** Let this routine reach outside the machine. */
    "allowExternalCalls": boolean;
    /** Exact set of tools it may use. Empty means the agent's usual registry, minus what the flags above withhold. */
    "allowedTools"?: unknown;
  };
    /** enabled or disabled. */
    "status"?: unknown;
    /** New triggers. Replaces the old ones whole; a webhook among them mints a new token. */
    "triggers"?: unknown;
  }; output: unknown };
  /** Install a skill package, from a script or an agent assembling one. */
  "skills_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Version to install — a tag or a commit. Empty installs whatever the source currently holds. */
    "ref"?: string;
    /** Where the package is. A local directory today. */
    "source": string;
  }; output: unknown };
  /** Uninstall a skill. */
  "skills_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the skill to uninstall. */
    "id": string;
  }; output: unknown };
  /** Install a skill package. */
  "skills_install": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Version to install — a tag or a commit. Empty installs whatever the source currently holds. */
    "ref"?: string;
    /** Where the package is. A local directory today. */
    "source": string;
  }; output: unknown };
  /** List every installed skill. */
  "skills_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Turn a skill's live behaviour on or off. */
  "skills_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Turn this skill's hooks and toolsets on (true) or off (false). Omit to leave unchanged. */
    "active"?: unknown;
    /** Identifier of the skill to update. */
    "id": string;
  }; output: unknown };
  /** Cut the isolated checkout a task executes in. */
  "tasks_branch": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Branch to cut from. */
    "base"?: string;
    /** Branch name. Generated from the workspace prefix and the task slug when left out. */
    "branch"?: string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** Record a unit of work. */
  "tasks_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug or user identifier. Only an agent is dispatched autonomously. */
    "assigned"?: string;
    /** Branch the checkout is cut from. */
    "base"?: string;
    /** The description and plan, in Markdown. */
    "content"?: string;
    /** Tasks that must finish before this one can start. */
    "dependsOn"?: unknown;
    /** RFC3339 instant it is due. */
    "dueAt"?: string;
    /** Goal this serves. */
    "goal"?: string;
    /** What the work is. Example: "Denial patterns never match a command line". */
    "name": string;
    /** One of: no_priority, urgent, high, medium, low. */
    "priority"?: string;
    /** Project this belongs to. */
    "project"?: string;
    /** Where it starts: suggestion, backlog, planning or todo. Defaults to backlog. */
    "status"?: string;
    /** One-paragraph statement of the work. */
    "summary"?: string;
    /** One of the workspace's task types. Example: "bug". */
    "type"?: string;
    /** Run this task in an isolated Git checkout. */
    "worktree"?: boolean;
  }; output: unknown };
  /** Remove a task and everything under it. */
  "tasks_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** Read one task. */
  "tasks_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** List the tasks. */
  "tasks_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only tasks owned by this agent or user. */
    "assigned"?: string;
    /** Only tasks serving this goal. */
    "goal"?: string;
    /** How many to return. */
    "limit"?: number;
    /** How many to skip. */
    "offset"?: number;
    /** Only tasks in this project. */
    "project"?: string;
    /** Only tasks in this status. */
    "status"?: string;
    /** Only tasks of this workspace type. Example: "bug". */
    "type"?: string;
  }; output: unknown };
  /** Move a task through its lifecycle. */
  "tasks_set-status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
    /** Why. Recorded on the checkpoint when stopping. */
    "reason"?: string;
    /** One of: suggestion, backlog, planning, todo, in_progress, stopped, in_review, finished. */
    "status": string;
  }; output: unknown };
  /** Change what a task says. */
  "tasks_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New owner. Empty unassigns. */
    "assigned"?: unknown;
    /** Conversation this task's execution runs in. */
    "chat"?: unknown;
    /** New description and plan, in Markdown. */
    "content"?: unknown;
    /** New dependency list. Replaces the old one whole. */
    "dependsOn"?: unknown;
    /** New due date, RFC3339. Empty clears it. */
    "dueAt"?: unknown;
    /** New goal. */
    "goal"?: unknown;
    /** Identifier of the task. */
    "id": string;
    /** New name. The slug follows it. */
    "name"?: unknown;
    /** New priority. */
    "priority"?: unknown;
    /** New project. */
    "project"?: unknown;
    /** Not writable here. Use set-status, which validates the move and runs the guards. */
    "status"?: string;
    /** New summary. */
    "summary"?: unknown;
    /** New workspace task type. */
    "type"?: unknown;
  }; output: unknown };
  /** Author a new template. */
  "templates_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The Liquid template body. */
    "content": string;
    /** What this template produces and when to use it. */
    "description"?: string;
    /** Identifier for the template. Also its file name: lowercase, digits, hyphen and underscore only. */
    "id": string;
    /** Human name of the template. */
    "name": string;
    /** Suggested relative output path for a render of this template. */
    "output"?: string;
    /** The skill this template ships with, when Scope is skill. */
    "skill"?: string;
    /** The variables this template's body expects. */
    "variables"?: unknown;
  }; output: unknown };
  /** Remove a template. */
  "templates_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the template to delete. */
    "id": string;
  }; output: unknown };
  /** Read one template's Liquid body and declared variables. */
  "templates_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the template. */
    "id": string;
  }; output: unknown };
  /** List templates, optionally filtered by skill or text. */
  "templates_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Filter by substring match against name and description. */
    "query"?: string;
    /** Filter to templates that ship with this skill. */
    "skill"?: string;
  }; output: unknown };
  /** Render a template's body against variables. */
  "templates_render": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the template to render. */
    "id": string;
    /** Values for the template's declared Variables. A missing Required variable with no Default refuses the render. */
    "variables"?: Record<string, unknown>;
    /** When true, also writes the rendered output to disk at the template's own (Liquid-rendered) Output path. Refused if the template declares no Output. Default false only returns the rendered text. */
    "write"?: boolean;
  }; output: unknown };
  /** Change an existing template. */
  "templates_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New Liquid body. Omit to leave unchanged. Re-validated as Liquid when given. */
    "content"?: unknown;
    /** New description. Omit to leave unchanged. */
    "description"?: unknown;
    /** Identifier of the template to update. */
    "id": string;
    /** New name. Omit to leave unchanged. */
    "name"?: unknown;
    /** New suggested output path. Omit to leave unchanged. */
    "output"?: unknown;
    /** New variable contract, replacing the old one wholesale. */
    "variables"?: unknown;
  }; output: unknown };
  /** Remove a theme you installed. */
  "themes_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the theme. */
    "id": string;
  }; output: unknown };
  /** Read one theme and what it renders to. */
  "themes_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Which palette to render. Defaults to both. */
    "appearance"?: string;
    /** Identifier of the theme. */
    "id": string;
    /** True when rendering for the desktop window, where a translucent background has something behind it. */
    "native"?: boolean;
  }; output: unknown };
  /** Add a theme of your own. */
  "themes_install": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Who made it. */
    "author"?: string;
    /** Identifier for the theme. Example: "my-theme". */
    "id": string;
    /** Human-readable name. Defaults to the identifier. */
    "name"?: string;
    /** Palettes by appearance. A theme with both light and dark can follow the system. */
    "variants": Record<string, {
    /** Primary accent, as a hex value. */
    "accent": string;
    /** How strongly derived layers separate from the surface, 0 to 100. 50 is neutral. */
    "contrast": number;
    /** Colour of text on the surface, as a hex value. */
    "ink": string;
    /** Corner rounding: none, sm, md or lg. */
    "radius"?: string;
    /** Colours by meaning: accent, success, warning, error, info, diffAdded, diffRemoved. */
    "semantic"?: Record<string, string>;
    /** Background colour of the application, as a hex value. */
    "surface": string;
    /** solid or blur. Blur asks the operating system for a translucent window. */
    "windows"?: string;
  }>;
  }; output: unknown };
  /** List the themes available. */
  "themes_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only themes that offer this appearance: light, dark or auto. */
    "appearance"?: string;
  }; output: unknown };
  /** Add a step to the plan. */
  "todos_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Notes on this step, in Markdown. */
    "content"?: string;
    /** Position in the plan. Left out, the step goes at the end. */
    "order"?: number;
    /** Identifier of the parent task. */
    "task": string;
    /** What this step is. Example: "Reproduce the failure in a test". */
    "title": string;
  }; output: unknown };
  /** Remove a step from the plan. */
  "todos_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the step. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read one step. */
  "todos_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the step. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read a task's plan. */
  "todos_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Move a step through its lifecycle. */
  "todos_set-status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** What you verified. Record it when finishing a step that was verifiable. */
    "evidence"?: string;
    /** Identifier of the step. */
    "id": string;
    /** One of: pending, in_progress, blocked, finished, skipped. */
    "status": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Change a step's description. */
  "todos_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New notes, in Markdown. */
    "content"?: unknown;
    /** What you verified, concretely. */
    "evidence"?: unknown;
    /** Identifier of the step. */
    "id": string;
    /** New position in the plan. */
    "order"?: unknown;
    /** Not writable here. Use set-status, which validates the move. */
    "status"?: string;
    /** Identifier of the parent task. */
    "task": string;
    /** New title. */
    "title"?: unknown;
  }; output: unknown };
  /** Run one tool of a connected toolset. */
  "toolsets_call": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the toolset to call. */
    "id": string;
    /** Arguments for the tool. Opaque to this service — call toolsets_get with schema:true first. */
    "input"?: unknown;
    /** Name of the tool, as published by the connected target. */
    "tool": string;
  }; output: unknown };
  /** Remove a toolset. */
  "toolsets_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the toolset to delete. */
    "id": string;
  }; output: unknown };
  /** Read one toolset's configuration. */
  "toolsets_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the toolset. */
    "id": string;
  }; output: unknown };
  /** Read one toolset's configuration, for editing. */
  "toolsets_get-config": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the toolset. */
    "id": string;
  }; output: unknown };
  /** List every configured toolset. */
  "toolsets_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Reconfigure a toolset. */
  "toolsets_update-config": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New argument list, replacing the old one wholesale. */
    "args"?: unknown;
    /** New base URL. Omit to leave unchanged. */
    "baseUrl"?: unknown;
    /** New command for mcp-server::stdio. Omit to leave unchanged. */
    "command"?: unknown;
    /** New description. Omit to leave unchanged. */
    "description"?: unknown;
    /** New environment, replacing the old one wholesale. */
    "env"?: Record<string, string>;
    /** New headers, replacing the old ones wholesale. */
    "headers"?: Record<string, string>;
    /** Identifier of the toolset to reconfigure. */
    "id": string;
    /** New lifecycle status: enabled or disabled. Omit to leave unchanged. */
    "status"?: unknown;
  }; output: unknown };
  /** Publish the local daemon on the public internet. */
  "tunnel_start": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Report whether the tunnel is running. */
  "tunnel_status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Tear the tunnel down. */
  "tunnel_stop": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Install a staged, verified release and restart the daemon. */
  "update_apply": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The staged release, as DownloadOutput.staged returned it. */
    "staged": {
    "binaries": Record<string, string>;
    "dir": string;
    "version": string;
  };
  }; output: unknown };
  /** Query the release channel. Never downloads anything. */
  "update_check": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** stable or beta. Defaults to stable. */
    "channel"?: string;
  }; output: unknown };
  /** Fetch and verify this platform's assets for a release. Nothing is installed yet. */
  "update_download": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The release to download, as CheckOutput.release returned it. */
    "release": {
    "assets": unknown;
    "channel": string;
    "checksumsUrl": string;
    "notes"?: string;
    "publishedAt": string;
    "signatureUrl": string;
    "version": string;
  };
  }; output: unknown };
  /** Report the current version and channel, without checking the network. */
  "update_status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** List the catalog of components a view can compose. */
  "views_components": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Compose a new view. */
  "views_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** What this view is for. */
    "description"?: string;
    /** Identifier for the view. Also its file name: lowercase, digits, hyphen and underscore only. */
    "id": string;
    /** Human name of the view. Example: "Deals by stage". */
    "name"?: string;
    /** user or skill. Defaults to user. */
    "scope"?: string;
    /** The skill this view ships with, when Scope is skill. */
    "skill"?: string;
    /** Where this view's data comes from. */
    "source": {
    /** Id of the collection this view's data comes from. */
    "collection": string;
    /** Field values a record must match, by field name. */
    "filter"?: Record<string, unknown>;
    /** Maximum number of records to render. 0 means no limit. */
    "limit"?: number;
    /** Fields to order the rows by, applied in order. */
    "sort"?: unknown;
  };
    /** Heading the frontend shows above the rendered tree. */
    "title"?: string;
    /** The composed tree of catalog components: {component, props?, bind?, children?, actions?}, nested arbitrarily. Call views_components first to see what a component accepts. */
    "tree": unknown;
  }; output: unknown };
  /** Remove a view. */
  "views_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the view to remove. */
    "id": string;
    /** The skill this view ships with, when it is skill-scoped. */
    "skill"?: string;
  }; output: unknown };
  /** Press a button in a view. */
  "views_execute-action": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the view the action belongs to. */
    "id": string;
    /** Arguments to invoke the command with, merged over the action's own declared input. */
    "input"?: Record<string, unknown>;
    /** Label of the action within the view's tree, as declared. */
    "label": string;
  }; output: unknown };
  /** Read one view's declaration. */
  "views_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the view. */
    "id": string;
    /** The skill this view ships with, when it is skill-scoped. Required to resolve one — views_list reports it on every entry. */
    "skill"?: string;
  }; output: unknown };
  /** List every declared view. */
  "views_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Resolve a view against its source data. */
  "views_render": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the view to render. */
    "id": string;
    /** The skill this view ships with, when it is skill-scoped. */
    "skill"?: string;
  }; output: unknown };
  /** Compose a view an agent did not have to design by hand. */
  "views_scaffold": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Id of the collection to compose a screen for. */
    "collection": string;
    /** table, board or detail. Defaults to table. */
    "kind"?: string;
  }; output: unknown };
  /** Register a workspace and lay it out. */
  "workspace_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Optional accent colour as a hex code. Example: "#5E6AD2". */
    "color"?: string;
    /** Optional logo URL. */
    "logo"?: string;
    /** Workspace name. The identifier is the slug of this name. Example: "Project Alpha". */
    "name": string;
    /** Tone, style and autonomy of the orchestrator agent created with the workspace. */
    "orchestrator"?: {
    /** How independently the orchestrator acts, from 0 to 1. */
    "autonomy"?: number;
    /** Display name of the orchestrator. Defaults to "Atlas". */
    "name"?: string;
    /** One of: concise, balanced, detailed. */
    "style"?: string;
    /** One of: efficient, friendly, professional, candid. */
    "tone"?: string;
  };
    /** Absolute path of the repository this workspace operates on. Omit to create one under the state directory. */
    "path"?: string;
  }; output: unknown };
  /** Unregister a workspace. */
  "workspace_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id to unregister. */
    "workspace": string;
  }; output: unknown };
  /** Read one workspace. */
  "workspace_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id. Omit to read the active one, taken from the environment. */
    "workspace"?: string;
  }; output: unknown };
  /** Register the repository you are standing in. */
  "workspace_introspect": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Repository to register. Defaults to the working directory. */
    "path"?: string;
  }; output: unknown };
  /** See what a workspace holds, by collection. */
  "workspace_inventory": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id. Omit to survey the active one. */
    "workspace"?: string;
  }; output: unknown };
  /** List the registered workspaces. */
  "workspace_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Include archived workspaces in the result. Off by default. */
    "includeArchived"?: boolean;
  }; output: unknown };
  /** Change fields of a workspace. */
  "workspace_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Fields to change, addressed by dotted path. Example: { "git.branchPrefix": "feat", "color": "#10b981" }. */
    "set": Record<string, unknown>;
    /** Workspace id. Omit to update the active one. */
    "workspace"?: string;
  }; output: unknown };
}

export type CommandKey = keyof CommandMap;
export type CommandInput<K extends CommandKey> = CommandMap[K]["input"];
export type CommandOutput<K extends CommandKey> = CommandMap[K]["output"];

/** Every command key, for a runtime check that the binary has what this build expects. */
export const COMMAND_KEYS = [
  "activity_delete",
  "activity_get",
  "activity_list",
  "activity_purge",
  "activity_read",
  "activity_read-all",
  "agents_create",
  "agents_delete",
  "agents_get",
  "agents_list",
  "agents_me",
  "agents_update",
  "approvals_decide",
  "approvals_list",
  "artifacts_create",
  "artifacts_delete",
  "artifacts_get",
  "artifacts_list",
  "artifacts_set-password",
  "artifacts_update",
  "chats_create",
  "chats_get",
  "chats_list",
  "chats_send",
  "collections_create",
  "collections_delete",
  "collections_get",
  "collections_list",
  "collections_records-create",
  "collections_records-delete",
  "collections_records-get",
  "collections_records-list",
  "collections_records-update",
  "comments_create",
  "comments_delete",
  "comments_get",
  "comments_list",
  "comments_update",
  "config_get",
  "config_update",
  "gateway_restart",
  "gateway_start",
  "gateway_status",
  "gateway_stop",
  "goals_create",
  "goals_delete",
  "goals_get",
  "goals_list",
  "goals_update",
  "instructions_create",
  "instructions_delete",
  "instructions_get",
  "instructions_list",
  "instructions_update",
  "jobs_get",
  "jobs_list",
  "jobs_purge",
  "jobs_recover",
  "jobs_stats",
  "marketplace_discovery",
  "marketplace_get",
  "marketplace_install",
  "memories_forget",
  "memories_graph",
  "memories_recall",
  "memories_reflect",
  "memories_store",
  "models_list",
  "projects_create",
  "projects_delete",
  "projects_get",
  "projects_list",
  "projects_update",
  "routines_create",
  "routines_delete",
  "routines_fire",
  "routines_get",
  "routines_list",
  "routines_rotate",
  "routines_runs",
  "routines_update",
  "skills_create",
  "skills_delete",
  "skills_install",
  "skills_list",
  "skills_update",
  "tasks_branch",
  "tasks_create",
  "tasks_delete",
  "tasks_get",
  "tasks_list",
  "tasks_set-status",
  "tasks_update",
  "templates_create",
  "templates_delete",
  "templates_get",
  "templates_list",
  "templates_render",
  "templates_update",
  "themes_delete",
  "themes_get",
  "themes_install",
  "themes_list",
  "todos_create",
  "todos_delete",
  "todos_get",
  "todos_list",
  "todos_set-status",
  "todos_update",
  "toolsets_call",
  "toolsets_delete",
  "toolsets_get",
  "toolsets_get-config",
  "toolsets_list",
  "toolsets_update-config",
  "tunnel_start",
  "tunnel_status",
  "tunnel_stop",
  "update_apply",
  "update_check",
  "update_download",
  "update_status",
  "views_components",
  "views_create",
  "views_delete",
  "views_execute-action",
  "views_get",
  "views_list",
  "views_render",
  "views_scaffold",
  "workspace_create",
  "workspace_delete",
  "workspace_get",
  "workspace_introspect",
  "workspace_inventory",
  "workspace_list",
  "workspace_update",
] as const;
