// GENERATED by `task gen-schema`. Do not edit.
//
// Every command the application publishes, as the input it takes and the output
// it returns. The generator reads the same registry the CLI, MCP and HTTP
// surfaces read, so a field changed in Go fails the build here rather than
// failing a screen for whoever opens it next.

export interface CommandMap {
  /** Remove one entry from the log. */
  "activity_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Read one entry in full. */
  "activity_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Read the workspace inbox. */
  "activity_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to apply. Defaults to you. */
    "actor"?: string;
    /** Only this event within the namespace. Example: "status_changed". */
    "event"?: string;
    /** How many to return. Defaults to 50. */
    "limit"?: number;
    /** Only entries about this kind of thing. Example: "task". */
    "namespace"?: string;
    /** How many to skip. */
    "offset"?: number;
    /** RFC3339 instant; only entries at or after it. */
    "since"?: string;
    /** Only what you have not read yet. */
    "unread"?: boolean;
  }; output: unknown };
  /** Drop entries past the retention window. */
  "activity_purge": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Override the retention window, in days. Defaults to the configured 90. */
    "olderThanDays"?: number;
  }; output: unknown };
  /** Mark one entry as read. */
  "activity_read": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to change. Defaults to you. */
    "actor"?: string;
    /** Identifier of the entry. */
    "id": string;
  }; output: unknown };
  /** Mark the whole inbox as read. */
  "activity_read-all": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose read state to change. Defaults to you. */
    "actor"?: string;
  }; output: unknown };
  /** Create an agent. */
  "agents_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Communication channel bindings for this agent. */
    "channels"?: unknown;
    /** Markdown system instructions for the agent runtime. */
    "content"?: string;
    /** Orchestrator-facing summary of when to delegate to this agent. */
    "description"?: string;
    /** Unique agent identifier (slug). Lowercase, no spaces. Example: "atlas". */
    "id": string;
    /** Slug of the leader agent in a hierarchical team. */
    "leader"?: string;
    /** LLM model id for this agent. Example: "gpt-4o". */
    "model"?: string;
    /** Human-readable display name. Defaults to the slug. */
    "name"?: string;
    /** Marks the workspace orchestrator fallback for non-direct chats. */
    "orchestrator"?: boolean;
    /** LLM provider slug for this agent. Example: "openai". */
    "provider"?: string;
    /** How hard this agent should think: none, low, medium or high. Defaults to the installation's setting. */
    "reasoning"?: string;
    /** Functional role label shown in delegation prompts. */
    "role"?: string;
    /** Filesystem and execution policy. Absent means read-only with no execution at all. */
    "sandbox"?: {
    /** Which programs this agent may run. */
    "exec"?: {
    /** Binary names or absolute paths this agent may run. Example: ["git", "go"]. */
    "allow"?: unknown;
    /** Whether this agent may reach a shell. A shell makes the allowlist a suggestion, so it takes its own opt-in. */
    "allowShell"?: boolean;
    /** Command lines to refuse even for an allowed binary. Example: ["git push --force*"]. */
    "denyArgs"?: unknown;
    /** allowlist or deny-all. Defaults to deny-all. */
    "policy"?: string;
  };
    /** Any of: read, write, delete, execute. Defaults to read alone. */
    "permissions"?: unknown;
  };
    /** Voice name for speech output. */
    "voice"?: string;
  }; output: unknown };
  /** Delete an agent and everything under it. */
  "agents_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug to delete. This removes the agent's memories and routines with it. */
    "id": string;
  }; output: unknown };
  /** Read one agent, instructions included. */
  "agents_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug to retrieve. Example: "neo". */
    "id": string;
  }; output: unknown };
  /** List the agents of the workspace. */
  "agents_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Maximum number of agents to return. 0 means no limit. */
    "limit"?: number;
    /** Only agents with this functional role label. */
    "role"?: string;
    /** Only agents shipped by this skill. Omit to list the workspace's own agents and every skill's. */
    "skill"?: string;
  }; output: unknown };
  /** Resolve your own identity in this workspace. */
  "agents_me": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Change an agent. */
  "agents_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New Markdown system instructions. Replaces the body entirely. */
    "content"?: unknown;
    /** New orchestrator-facing summary. */
    "description"?: unknown;
    /** Agent slug to update. */
    "id": string;
    /** New leader slug. */
    "leader"?: unknown;
    /** New LLM model id. */
    "model"?: unknown;
    /** New display name. */
    "name"?: unknown;
    /** Whether this agent is the workspace orchestrator. */
    "orchestrator"?: unknown;
    /** New LLM provider slug. */
    "provider"?: unknown;
    /** New reasoning level: none, low, medium or high. */
    "reasoning"?: unknown;
    /** New functional role label. */
    "role"?: unknown;
    /** New filesystem and execution policy. Replaces the block entirely. */
    "sandbox"?: {
    /** Which programs this agent may run. */
    "exec"?: {
    /** Binary names or absolute paths this agent may run. Example: ["git", "go"]. */
    "allow"?: unknown;
    /** Whether this agent may reach a shell. A shell makes the allowlist a suggestion, so it takes its own opt-in. */
    "allowShell"?: boolean;
    /** Command lines to refuse even for an allowed binary. Example: ["git push --force*"]. */
    "denyArgs"?: unknown;
    /** allowlist or deny-all. Defaults to deny-all. */
    "policy"?: string;
  };
    /** Any of: read, write, delete, execute. Defaults to read alone. */
    "permissions"?: unknown;
  };
    /** New voice name. */
    "voice"?: unknown;
  }; output: unknown };
  /** Allow or refuse a waiting tool call. */
  "approvals_decide": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** True to let the call run, false to refuse it. */
    "approved": boolean;
    /** Identifier of the waiting request. */
    "id": string;
    /** Why. A refusal without one leaves the agent guessing what to try instead. */
    "reason"?: string;
    /** none, session or always. Defaults to none — approving once is not approving forever. */
    "remember"?: string;
    /** A corrected payload to run instead of the one proposed. */
    "updatedInput"?: unknown;
  }; output: unknown };
  /** List the tool calls waiting for a decision. */
  "approvals_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Open a conversation. */
  "chats_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent that owns this conversation, for run transcripts. */
    "agent"?: string;
    /** External messenger to bind it to. */
    "channel"?: {
    /** Conversation identifier on the provider. */
    "chatId": string;
    /** Messaging provider slug. Example: "telegram". */
    "provider": string;
    /** User identifier on the provider. */
    "userId"?: string;
  };
    /** One of: dm, channel, task, run, external. Defaults to channel. */
    "kind"?: string;
    /** Who is in it. Empty on a workspace-visible channel means everyone. */
    "participants"?: unknown;
    /** Routine this conversation belongs to. */
    "routine"?: string;
    /** Task this conversation belongs to. */
    "task"?: string;
    /** What to call it. */
    "title": string;
    /** private or workspace. Defaults to workspace. */
    "visibility"?: string;
  }; output: unknown };
  /** Read one conversation. */
  "chats_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the conversation. */
    "chat": string;
  }; output: unknown };
  /** List conversations. */
  "chats_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Narrow to one surface: dm, channel, task, run or external. */
    "kind"?: string;
    /** Maximum number to return. Defaults to 50. */
    "limit"?: number;
    /** Filter by title, identifier, task or routine. */
    "query"?: string;
    /** Only conversations attached to this routine. */
    "routine"?: string;
    /** Only conversations attached to this task. */
    "task"?: string;
  }; output: unknown };
  /** Write to a conversation. */
  "chats_send": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Answer with this agent regardless of what the text mentions. */
    "agent"?: string;
    /** Conversation to write to. */
    "chat": string;
    /** What to say. Address a specific agent with @slug. */
    "text": string;
  }; output: unknown };
  /** Write a comment on a task. */
  "comments_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The comment, in Markdown. */
    "body": string;
    /** Comment this replies to. A reply to a reply joins the same thread. */
    "parent"?: string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Remove a comment you wrote. */
  "comments_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read one comment. */
  "comments_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read a task's discussion. */
  "comments_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Rewrite a comment you wrote. */
  "comments_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** The new body, in Markdown. */
    "body": string;
    /** Identifier of the comment. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read the configuration, with secrets redacted. */
  "config_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Show secret values in full. Only honoured for a human on an interactive terminal; an agent never receives unredacted secrets. */
    "reveal"?: boolean;
  }; output: unknown };
  /** Change configuration fields by dotted path. */
  "config_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Dotted paths to set, for example {"region.timezone": "America/Sao_Paulo"}. An agent may only set fields on the agent-writable allowlist. */
    "set": Record<string, unknown>;
  }; output: unknown };
  /** Stop the daemon and start it again. */
  "gateway_restart": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Start the daemon. */
  "gateway_start": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Report whether the daemon is running. */
  "gateway_status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Stop the daemon. */
  "gateway_stop": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** Read one job. */
  "jobs_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the job. */
    "id": string;
  }; output: unknown };
  /** List the queued work. */
  "jobs_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only jobs of this handler kind. */
    "kind"?: string;
    /** How many to return, newest first. */
    "limit"?: number;
    /** One of: chat, task, routine, workspace. */
    "queue"?: string;
    /** One of: pending, claimed, succeeded, failed, dead. */
    "status"?: string;
    /** Only jobs of this workspace. */
    "workspace"?: string;
  }; output: unknown };
  /** Remove finished jobs older than the window. */
  "jobs_purge": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Override the window, in days. Defaults to 7. */
    "olderThanDays"?: number;
  }; output: unknown };
  /** Hand back work whose worker stopped reporting. */
  "jobs_recover": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
  }; output: unknown };
  /** The shape of the queue right now. */
  "jobs_stats": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only jobs of this workspace. */
    "workspace"?: string;
  }; output: unknown };
  /** Deprecate knowledge that no longer holds. */
  "memories_forget": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memory it is. Defaults to your own. */
    "agent"?: string;
    /** Identifier of the memory to deprecate. */
    "memory": string;
    /** Why this knowledge no longer holds. Be specific: a vague reason confuses your future self. */
    "reason": string;
  }; output: unknown };
  /** Map your cognitive graph. */
  "memories_graph": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose graph to map. Defaults to your own. */
    "agent"?: string;
    /** Narrow the graph to one category. */
    "category"?: string;
    /** Return only the memories with no links at all — the ones most likely to be lost. */
    "isolated"?: boolean;
    /** Maximum number of nodes. Defaults to 1000. */
    "limit"?: number;
    /** Exclude memories below this confidence. */
    "minConfidence"?: number;
    /** Glob patterns narrowing the graph to memories anchored to these files. */
    "scopes"?: unknown;
    /** strict excludes memories with no scopes; lax includes them. Defaults to lax. */
    "scopesMode"?: string;
  }; output: unknown };
  /** Scan your memories. */
  "memories_recall": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memories to read. Defaults to your own. */
    "agent"?: string;
    /** Narrow to one category. */
    "category"?: string;
    /** Reverse the ordering. */
    "desc"?: boolean;
    /** Maximum number of memories to return. Defaults to 10. */
    "limit"?: number;
    /** How many matches to skip. */
    "offset"?: number;
    /** One of: relevance, confidence, createdAt, updatedAt. Defaults to relevance when searching, and to createdAt otherwise. */
    "orderBy"?: string;
    /** Full-text search across title, description, tags and body. Every word must appear somewhere. */
    "query"?: string;
    /** Glob patterns anchoring the search to files. Example: ["internal/domain/**"]. */
    "scopes"?: unknown;
    /** strict excludes memories with no scopes; lax includes them. Defaults to lax. */
    "scopesMode"?: string;
    /** Lifecycle status to include. Defaults to active. */
    "status"?: string;
  }; output: unknown };
  /** Read one memory in full. */
  "memories_reflect": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose memory it is. Defaults to your own. */
    "agent"?: string;
    /** Identifier of the memory to read. */
    "memory": string;
  }; output: unknown };
  /** Record durable knowledge. */
  "memories_store": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** One of: decision, intent, commitment, relationship, event, observation, error, learning, fact, reference, instruction, preference, context. */
    "category": string;
    /** From 0 to 1. Defaults to 1. Be honest — an inflated number is how future-you gets misled. */
    "confidence"?: unknown;
    /** The Markdown body of the memory. */
    "content"?: string;
    /** Dense, keyword-rich summary written to be found by search. */
    "description": string;
    /** RFC 3339 timestamp after which this memory stops applying. */
    "expiresAt"?: string;
    /** Identifiers of related memories. Aim for one or two whenever related traces exist. */
    "links"?: unknown;
    /** Glob patterns anchoring this memory to the files that gave rise to it. */
    "scopes"?: unknown;
    /** Memories this one replaces, each with the reason it no longer applies. */
    "supersedes"?: unknown;
    /** Labels grouping related knowledge. */
    "tags"?: unknown;
    /** Sharp, specific headline. It is what you will scan later. */
    "title": string;
  }; output: unknown };
  /** Declare a routine. */
  "routines_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** The routine's prompt: what to do when it fires. */
    "content"?: string;
    /** What the routine does. Example: "Triage new bugs each morning". */
    "name": string;
    /** What it is allowed to do when it runs. */
    "scope"?: {
    /** Let this routine create tasks. */
    "allowCreateTasks": boolean;
    /** Let this routine reach outside the machine. */
    "allowExternalCalls": boolean;
    /** Exact set of tools it may use. Empty means the agent's usual registry, minus what the flags above withhold. */
    "allowedTools"?: unknown;
  };
    /** enabled or disabled. Defaults to enabled. */
    "status"?: string;
    /** What makes it fire. Without one it only fires by hand. */
    "triggers"?: unknown;
  }; output: unknown };
  /** Remove a routine and its runs. */
  "routines_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** Run a routine now. */
  "routines_fire": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Fire even if the routine is disabled. */
    "force"?: boolean;
    /** Identifier of the routine. */
    "id": string;
    /** What to hand the routine. */
    "payload"?: Record<string, unknown>;
    /** What to record as the cause. Defaults to manual. */
    "trigger"?: string;
  }; output: unknown };
  /** Read one routine. */
  "routines_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** List the routines. */
  "routines_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routines. Defaults to yours. */
    "agent"?: string;
    /** Only enabled or only disabled. */
    "status"?: string;
  }; output: unknown };
  /** Mint a new webhook token. */
  "routines_rotate": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
  }; output: unknown };
  /** Read a routine's audit history. */
  "routines_runs": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** Identifier of the routine. */
    "id": string;
    /** How many to return, newest first. */
    "limit"?: number;
  }; output: unknown };
  /** Change a routine. */
  "routines_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Whose routine. Defaults to yours. */
    "agent"?: string;
    /** New prompt. */
    "content"?: unknown;
    /** Identifier of the routine. */
    "id": string;
    /** New name. */
    "name"?: unknown;
    /** New scope. */
    "scope"?: {
    /** Let this routine create tasks. */
    "allowCreateTasks": boolean;
    /** Let this routine reach outside the machine. */
    "allowExternalCalls": boolean;
    /** Exact set of tools it may use. Empty means the agent's usual registry, minus what the flags above withhold. */
    "allowedTools"?: unknown;
  };
    /** enabled or disabled. */
    "status"?: unknown;
    /** New triggers. Replaces the old ones whole; a webhook among them mints a new token. */
    "triggers"?: unknown;
  }; output: unknown };
  /** Cut the isolated checkout a task executes in. */
  "tasks_branch": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Branch to cut from. */
    "base"?: string;
    /** Branch name. Generated from the workspace prefix and the task slug when left out. */
    "branch"?: string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** Record a unit of work. */
  "tasks_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Agent slug or user identifier. Only an agent is dispatched autonomously. */
    "assigned"?: string;
    /** Branch the checkout is cut from. */
    "base"?: string;
    /** The description and plan, in Markdown. */
    "content"?: string;
    /** Tasks that must finish before this one can start. */
    "dependsOn"?: unknown;
    /** RFC3339 instant it is due. */
    "dueAt"?: string;
    /** Goal this serves. */
    "goal"?: string;
    /** What the work is. Example: "Denial patterns never match a command line". */
    "name": string;
    /** One of: no_priority, urgent, high, medium, low. */
    "priority"?: string;
    /** Project this belongs to. */
    "project"?: string;
    /** Where it starts: suggestion, backlog, planning or todo. Defaults to backlog. */
    "status"?: string;
    /** One-paragraph statement of the work. */
    "summary"?: string;
    /** One of the workspace's task types. Example: "bug". */
    "type"?: string;
    /** Run this task in an isolated Git checkout. */
    "worktree"?: boolean;
  }; output: unknown };
  /** Remove a task and everything under it. */
  "tasks_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** Read one task. */
  "tasks_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
  }; output: unknown };
  /** List the tasks. */
  "tasks_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only tasks owned by this agent or user. */
    "assigned"?: string;
    /** Only tasks serving this goal. */
    "goal"?: string;
    /** How many to return. */
    "limit"?: number;
    /** How many to skip. */
    "offset"?: number;
    /** Only tasks in this project. */
    "project"?: string;
    /** Only tasks in this status. */
    "status"?: string;
    /** Only tasks of this workspace type. Example: "bug". */
    "type"?: string;
  }; output: unknown };
  /** Move a task through its lifecycle. */
  "tasks_set-status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the task. */
    "id": string;
    /** Why. Recorded on the checkpoint when stopping. */
    "reason"?: string;
    /** One of: suggestion, backlog, planning, todo, in_progress, stopped, in_review, finished. */
    "status": string;
  }; output: unknown };
  /** Change what a task says. */
  "tasks_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New owner. Empty unassigns. */
    "assigned"?: unknown;
    /** Conversation this task's execution runs in. */
    "chat"?: unknown;
    /** New description and plan, in Markdown. */
    "content"?: unknown;
    /** New dependency list. Replaces the old one whole. */
    "dependsOn"?: unknown;
    /** New due date, RFC3339. Empty clears it. */
    "dueAt"?: unknown;
    /** New goal. */
    "goal"?: unknown;
    /** Identifier of the task. */
    "id": string;
    /** New name. The slug follows it. */
    "name"?: unknown;
    /** New priority. */
    "priority"?: unknown;
    /** New project. */
    "project"?: unknown;
    /** Not writable here. Use set-status, which validates the move and runs the guards. */
    "status"?: string;
    /** New summary. */
    "summary"?: unknown;
    /** New workspace task type. */
    "type"?: unknown;
  }; output: unknown };
  /** Remove a theme you installed. */
  "themes_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the theme. */
    "id": string;
  }; output: unknown };
  /** Read one theme and what it renders to. */
  "themes_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Which palette to render. Defaults to both. */
    "appearance"?: string;
    /** Identifier of the theme. */
    "id": string;
    /** True when rendering for the desktop window, where a translucent background has something behind it. */
    "native"?: boolean;
  }; output: unknown };
  /** Add a theme of your own. */
  "themes_install": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Who made it. */
    "author"?: string;
    /** Identifier for the theme. Example: "my-theme". */
    "id": string;
    /** Human-readable name. Defaults to the identifier. */
    "name"?: string;
    /** Palettes by appearance. A theme with both light and dark can follow the system. */
    "variants": Record<string, {
    /** Primary accent, as a hex value. */
    "accent": string;
    /** How strongly derived layers separate from the surface, 0 to 100. 50 is neutral. */
    "contrast": number;
    /** Colour of text on the surface, as a hex value. */
    "ink": string;
    /** Corner rounding: none, sm, md or lg. */
    "radius"?: string;
    /** Colours by meaning: accent, success, warning, error, info, diffAdded, diffRemoved. */
    "semantic"?: Record<string, string>;
    /** Background colour of the application, as a hex value. */
    "surface": string;
    /** solid or blur. Blur asks the operating system for a translucent window. */
    "windows"?: string;
  }>;
  }; output: unknown };
  /** List the themes available. */
  "themes_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Only themes that offer this appearance: light, dark or auto. */
    "appearance"?: string;
  }; output: unknown };
  /** Add a step to the plan. */
  "todos_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Notes on this step, in Markdown. */
    "content"?: string;
    /** Position in the plan. Left out, the step goes at the end. */
    "order"?: number;
    /** Identifier of the parent task. */
    "task": string;
    /** What this step is. Example: "Reproduce the failure in a test". */
    "title": string;
  }; output: unknown };
  /** Remove a step from the plan. */
  "todos_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the step. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read one step. */
  "todos_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the step. */
    "id": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Read a task's plan. */
  "todos_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Move a step through its lifecycle. */
  "todos_set-status": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** What you verified. Record it when finishing a step that was verifiable. */
    "evidence"?: string;
    /** Identifier of the step. */
    "id": string;
    /** One of: pending, in_progress, blocked, finished, skipped. */
    "status": string;
    /** Identifier of the parent task. */
    "task": string;
  }; output: unknown };
  /** Change a step's description. */
  "todos_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** New notes, in Markdown. */
    "content"?: unknown;
    /** What you verified, concretely. */
    "evidence"?: unknown;
    /** Identifier of the step. */
    "id": string;
    /** New position in the plan. */
    "order"?: unknown;
    /** Not writable here. Use set-status, which validates the move. */
    "status"?: string;
    /** Identifier of the parent task. */
    "task": string;
    /** New title. */
    "title"?: unknown;
  }; output: unknown };
  /** Register a workspace and lay it out. */
  "workspace_create": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Optional accent colour as a hex code. Example: "#5E6AD2". */
    "color"?: string;
    /** Optional logo URL. */
    "logo"?: string;
    /** Workspace name. The identifier is the slug of this name. Example: "Project Alpha". */
    "name": string;
    /** Tone, style and autonomy of the orchestrator agent created with the workspace. */
    "orchestrator"?: {
    /** How independently the orchestrator acts, from 0 to 1. */
    "autonomy"?: number;
    /** Display name of the orchestrator. Defaults to "Atlas". */
    "name"?: string;
    /** One of: concise, balanced, detailed. */
    "style"?: string;
    /** One of: efficient, friendly, professional, candid. */
    "tone"?: string;
  };
    /** Absolute path of the repository this workspace operates on. Omit to create one under the state directory. */
    "path"?: string;
  }; output: unknown };
  /** Unregister a workspace. */
  "workspace_delete": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id to unregister. */
    "workspace": string;
  }; output: unknown };
  /** Read one workspace. */
  "workspace_get": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id. Omit to read the active one, taken from the environment. */
    "workspace"?: string;
  }; output: unknown };
  /** Register the repository you are standing in. */
  "workspace_introspect": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Repository to register. Defaults to the working directory. */
    "path"?: string;
  }; output: unknown };
  /** See what a workspace holds, by collection. */
  "workspace_inventory": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Workspace id. Omit to survey the active one. */
    "workspace"?: string;
  }; output: unknown };
  /** List the registered workspaces. */
  "workspace_list": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Include archived workspaces in the result. Off by default. */
    "includeArchived"?: boolean;
  }; output: unknown };
  /** Change fields of a workspace. */
  "workspace_update": { input: {
    /** MANDATORY. NEVER FORGET. Explain why this specific tool is being called now, what outcome you expect, and the immediate next step if that helps clarify the call. Do not leave this empty. */
    "_reasoning": string;
    /** Fields to change, addressed by dotted path. Example: { "git.branchPrefix": "feat", "color": "#10b981" }. */
    "set": Record<string, unknown>;
    /** Workspace id. Omit to update the active one. */
    "workspace"?: string;
  }; output: unknown };
}

export type CommandKey = keyof CommandMap;
export type CommandInput<K extends CommandKey> = CommandMap[K]["input"];
export type CommandOutput<K extends CommandKey> = CommandMap[K]["output"];

/** Every command key, for a runtime check that the binary has what this build expects. */
export const COMMAND_KEYS = [
  "activity_delete",
  "activity_get",
  "activity_list",
  "activity_purge",
  "activity_read",
  "activity_read-all",
  "agents_create",
  "agents_delete",
  "agents_get",
  "agents_list",
  "agents_me",
  "agents_update",
  "approvals_decide",
  "approvals_list",
  "chats_create",
  "chats_get",
  "chats_list",
  "chats_send",
  "comments_create",
  "comments_delete",
  "comments_get",
  "comments_list",
  "comments_update",
  "config_get",
  "config_update",
  "gateway_restart",
  "gateway_start",
  "gateway_status",
  "gateway_stop",
  "jobs_get",
  "jobs_list",
  "jobs_purge",
  "jobs_recover",
  "jobs_stats",
  "memories_forget",
  "memories_graph",
  "memories_recall",
  "memories_reflect",
  "memories_store",
  "routines_create",
  "routines_delete",
  "routines_fire",
  "routines_get",
  "routines_list",
  "routines_rotate",
  "routines_runs",
  "routines_update",
  "tasks_branch",
  "tasks_create",
  "tasks_delete",
  "tasks_get",
  "tasks_list",
  "tasks_set-status",
  "tasks_update",
  "themes_delete",
  "themes_get",
  "themes_install",
  "themes_list",
  "todos_create",
  "todos_delete",
  "todos_get",
  "todos_list",
  "todos_set-status",
  "todos_update",
  "workspace_create",
  "workspace_delete",
  "workspace_get",
  "workspace_introspect",
  "workspace_inventory",
  "workspace_list",
  "workspace_update",
] as const;
